---
driver:
  name: docker
  hostname: salt.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: salt
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - salt
  pillars:
    top.sls:
      base:
        "*":
          - salt
          - common
    common.sls:
      salt:
        minion:
          enabled: true
          master:
            host: localhost
      linux:
        system:
          enabled: true
          name: salt
          domain: ci.local
  dependencies:
    - name: git
      repo: git
      source: https://github.com/salt-formulas/salt-formula-git.git
    - name: reclass
      repo: git
      source: https://github.com/salt-formulas/salt-formula-reclass.git

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-trusty
    driver_config:
      image: trevorj/salty-whales:trusty
      platform: ubuntu

  - name: ubuntu-xenial
    driver_config:
      image: trevorj/salty-whales:xenial
      platform: ubuntu

suites:

  - name: minion-default
    provisioner:
      pillars:
        top.sls:
          base:
            "*":
              - common
              - minion_pki
              - minion_mine
              - minion_graph
              - minion_handler
      pillars-from-files:
        minion_pki.sls: tests/pillar/minion_pki_ca.sls
        minion_mine.sls: tests/pillar/minion_mine.sls
        minion_graph.sls: tests/pillar/minion_graph.sls
        minion_handler.sls: tests/pillar/minion_custom_handler.sls

  - name: master-default
    provisioner:
      pillars:
        top.sls:
          base:
            "*":
              - common
              - master_api
              - master_acl
              - master_ssh_key
              - master_ssh_password
              - master_ssh_root
              - master_handler
      pillars-from-files:
        master_api.sls: tests/pillar/master_acl.sls
        master_acl.sls: tests/pillar/master_api.sls
        master_ssh_key.sls: tests/pillar/master_ssh_minion_key.sls
        master_ssh_password.sls: tests/pillar/master_ssh_minion_password.sls
        master_ssh_root.sls: tests/pillar/master_ssh_minion_root.sls
        master_handler.sls: tests/pillar/master_custom_handler.sls

  - name: control_cloud_digitalocean
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/control_cloud_digitalocean.sls

  - name: control_cloud_openstack
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/control_cloud_openstack.sls

  - name: control_virt
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/control_virt.sls

  - name: master_single_pillar
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/master_single_pillar.sls

  - name: master_single_reclass
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/master_single_reclass.sls

  - name: minion_local_pillar
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/minion_local_pillar.sls

  - name: minion_local_reclass
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/minion_local_reclass.sls

  - name: minion_multi_master_failover
    provisioner:
      pillars-from-files:
        salt.sls: tests/pillar/minion_multi_master_failover.sls


  # vim: ft=yaml sw=2 ts=2 sts=2 tw=125
